@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\vite@8.1.5\node_modules\vite\node_modules;D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\vite@8.1.5\node_modules;D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\vite@8.1.5\node_modules\vite\node_modules;D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\vite@8.1.5\node_modules;D:\uon\学生竞赛2.0\vue-platform\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\vite\bin\vite.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\vite\bin\vite.js" %*
)
